internal/pkg/connectors/stripe/translate.go

fix: stripe transactions having no payouts were causing panic

---

.golangci.yml
Makefile
internal/pkg/connectors/dummypay/config.go
internal/pkg/connectors/dummypay/config_test.go
internal/pkg/connectors/dummypay/errors.go
internal/pkg/connectors/dummypay/loader.go
internal/pkg/connectors/dummypay/loader_test.go
internal/pkg/connectors/dummypay/task_generate_file.go
internal/pkg/connectors/dummypay/task_read_files.go
internal/pkg/ingestion/ingester.go
internal/pkg/ingestion/ingester_test.go
internal/pkg/payments/collections.go
internal/pkg/payments/metadata.go
internal/pkg/payments/payment.go

feat: payments metadata

---

internal/pkg/connectors/dummypay/task_descriptor.go
internal/pkg/connectors/dummypay/task_generate_file.go
internal/pkg/connectors/dummypay/task_ingest.go
internal/pkg/connectors/dummypay/task_read_files.go
internal/pkg/connectors/modulr/connector.go
internal/pkg/connectors/modulr/task_fetch_accounts.go
internal/pkg/connectors/modulr/task_resolve.go
internal/pkg/connectors/stripe/connector.go
internal/pkg/connectors/stripe/descriptor.go
internal/pkg/connectors/stripe/task_main.go
internal/pkg/connectors/wise/connector.go
internal/pkg/connectors/wise/task_fetch_profiles.go
internal/pkg/connectors/wise/task_resolve.go

feat: human readable names for connector tasks

---

docs/connectors.md

feat: extended connectors documentation

---

internal/app/api/connector.go
internal/app/integration/manager.go
internal/app/storage/task.go
internal/app/task/scheduler.go
internal/app/task/store.go
internal/app/task/storememory.go

feat: add pagination to tasks list

---

internal/app/task/scheduler.go

fix: print error log instead of crashing scheduler

---

internal/app/api/connector.go
internal/app/api/stripe.go

fix: add logic for checking whether connector is installed

---

internal/app/storage/accounts.go
internal/app/storage/paginate.go
internal/app/storage/paginate_test.go
internal/app/storage/payments.go
internal/app/storage/repository.go
internal/app/storage/task.go

A bug caused the previous cursor to appear in API responses even if no last data was available.

fix: pagination logic when using previous cursor

---

internal/connectors/engine/workflow/plugin_workflow.go
internal/connectors/engine/workflow/terminate_workflows.go
internal/connectors/engine/workflow/uninstall_connector.go

When having a connector with lots of data, we can have lots of workflows. When uninstalling, we will go through the workflows to terminated them, but we will maybe exceed the history size or length of a worfklow.
This PR adds two things: the termination of workflows in background and continue a new if we reach the limits

fix(temporal): continue a new when terminating workflows

---

internal/connectors/engine/workflow/context.go
internal/connectors/engine/workflow/install_connector.go

fixes: ENG-1533
this fixes the "Stdout already set" errors from the plugin client that sometimes occur on the dev cluster.

feat: (payments v3) Disable connector install retry in temporal workflow

---

go.mod
go.sum

fixes: ENG-1546
metricsProvider is already provided in the fx Options chain, so the SDK metrics become enabled without any code changes

feat: (metrics) update go-libs version to enable temporal SDK metrics

---

internal/connectors/engine/activities/temporal_schedule_create.go
internal/connectors/engine/workflow/create_payout.go
internal/connectors/engine/workflow/create_transfer.go
internal/connectors/engine/workflow/plugin_workflow.go

We launch the schedule before inserting it in the
database, so we can have instances inserted before schedule is inserted leading to errors.
Fixes ENG-1569

fix(temporal): fix missing reference storage error

---

internal/connectors/engine/engine.go
internal/connectors/engine/workers.go

When payments is rebooting, we do not recreate the default worker unless a connector is currently being deleted. This may cause a bug with workflows to create accounts, payments or pools
Fixes ENG-1570

fix(temporal): fix missing default worker

---

internal/api/v2/handler_connectors_install.go
test/e2e/api_accounts_test.go
test/e2e/api_bank_accounts_test.go
test/e2e/api_connectors_test.go
test/e2e/api_payments_test.go
test/e2e/api_pools_test.go

fixes: ENG-1575
```
$ fctl payments connectors install moneycorp moneycorp.json
You are about to install connector 'moneycorp'.
Do you want to continue [Y/n]y
SUCCESS  Connector installed!
SUCCESS  moneycorp: connector 'eyJQcm92aWRlciI6Im1vbmV5Y29ycCIsIlJlZmVyZW5jZSI6IjYxMDc2ZTc0LWZhNmMtNGE5Yy04OGFkLTdhYmRjODEyZjdkZiJ9' installed!
```

fix: (v2) ensure connector install v2 response is compatible to fctl

---

openapi/v3/v3-api.yaml

This PR allows us to call the sdk like that: `sdk.Payments.V3.GetPayments` instead of `sdk.Payments.V3.V3GetPayments` which was adding a repetition of the version in the name

feat(openapi): override v3 name

---

.codecov.yml
Earthfile
go.mod
internal/storage/accounts_test.go
internal/storage/balances_test.go
internal/storage/bank_accounts_test.go
internal/storage/migrations.go
internal/storage/migrations/1-migrate-connectors-from-v2.go
internal/storage/migrations/10-migrate-payments-reversal.go
internal/storage/migrations/2-migrate-accounts-events-from-v2.go
internal/storage/migrations/3-migrate-payments-events-from-v2.go
internal/storage/migrations/4-migrate-balances-events-from-v2.go
internal/storage/migrations/8-migrate-transfer-initiation-adjustments-from-v2.go
internal/storage/migrations/main_test.go
internal/storage/migrations/migrations.go
internal/storage/migrations/migrations_test.go
internal/storage/migrations/v2_migrations_test.sql
internal/storage/payment_initiation_reversals_test.go
internal/storage/payment_initiations_test.go
internal/storage/payments_test.go
internal/storage/pools_test.go
internal/storage/schedules_test.go
internal/storage/webhooks_configs_test.go
internal/storage/workflow_instances_test.go

feat(storage): more tests

---

internal/api/backend/backend.go
internal/api/backend/backend_generated.go
internal/api/services/connectors_config_update.go
internal/api/services/connectors_config_update_test.go
internal/api/v3/handler_connectors_config_update.go
internal/api/v3/handler_connectors_config_update_test.go
internal/api/v3/handler_connectors_install.go
internal/api/v3/handler_connectors_install_test.go
internal/api/v3/utils.go
internal/connectors/engine/engine.go
internal/connectors/engine/engine_generated.go
internal/connectors/engine/module.go
internal/connectors/engine/plugins/plugin.go
internal/connectors/engine/plugins/plugin_generated.go
internal/worker/module.go
test/e2e/api_connectors_test.go

feat: (validation) check connector config payload more thoroughly before inserting into the DB

---

internal/api/v2/handler_accounts_balances.go

Even if it's deprecated in the openapi.yml, we still need to support it for the time being

fix(api): fix missing currency for v2 balances endpoint

---

internal/connectors/engine/activities/temporal_schedule_create.go
internal/connectors/engine/activities/temporal_schedule_create_test.go
internal/connectors/plugins/public/atlar/workflow.go

Needed for the Atlar connector because we fetch everything at every polling (since Atlar does not provide a good pagination api)

fix(temporal): fix schedule already running error

---

internal/connectors/engine/workflow/install_connector.go
internal/connectors/engine/workflow/install_connector_test.go

When pod is restarting, the install method is called again but failed since the child workflow run is already started, leading to the connector being dropped.

fix(temporal): fix already started run workflow

---

internal/models/payment_initiation_type.go
internal/storage/migrations/7-migrate-transfer-initiations-from-v2.sql
internal/storage/migrations/migrations_test.go
openapi/v1-2/v1-2.yaml

This commit fixes the openapi required connectorID that is not required and payment initiation type

fix(payments): fix after sdk testing from the team

---

internal/connectors/engine/activities/errors.go
internal/storage/payments.go
internal/storage/payments_test.go

Sometimes, we can have two refunds for the same payment inside the same batch, and postgres does not support it and return an error 'command cannot affect row a second time'

fix(storage): de-duplicate payments when updating db

---

internal/storage/balances.go
internal/storage/balances_test.go

balance endpoint now returns when there's no balance data for the account
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 27 Jan 2025 13:00:07 GMT
Content-Length: 53
{"cursor":{"pageSize":15,"hasMore":false,"data":[]}}
```

fix(balances): return empty list balances response instead of nil

---

internal/storage/payments.go
internal/storage/payments_test.go

Mor modulr, when we create a transfer/payout, we will have the same date for pending/succeeded transaction, so the only thing differenciating the two is the sort_id we added. That way, we can have the last status in the main payment

fix(storage): fix payment list sorting

---

internal/models/payment_initiations.go

If scheduleAt is empty, we have to take the createdAt

fix(paymentinitiations): fix created at sent to the workflow

---

internal/connectors/plugins/public/stripe/client/payouts.go
internal/models/accounts.go
internal/models/accounts_test.go

issue 1: payouts were made using an unauthenticated client
issue 2: when using an implied root account the conversion to PSPAccount panicked

fix(stripe): fix issues when making payouts and transfers using root account

---

go.mod
internal/api/v2/handler_test.go
internal/api/v2/handler_transfer_initiations_create.go
internal/api/v2/handler_transfer_initiations_create_test.go
internal/api/v2/handler_transfer_initiations_reverse.go
internal/api/v2/handler_transfer_initiations_reverse_test.go
internal/api/v2/router.go
internal/api/v3/handler_payment_initiations_create.go
internal/api/v3/handler_payment_initiations_create_test.go
internal/api/v3/handler_payment_initiations_reverse.go
internal/api/v3/handler_payment_initiations_reverse_test.go
internal/api/v3/router.go
internal/api/v3/utils.go
internal/api/validation/checkers.go
internal/api/validation/validation.go
internal/api/validation/validation_test.go
openapi.yaml
openapi/v3/v3-schemas.yaml
test/e2e/api_payment_initiations_test.go

Fixes: ENG-1636
Some examples of error responses messages provided by library:
```
{"errorCode":"VALIDATION","errorMessage":"Reference is a required field"}
{"errorCode":"VALIDATION","errorMessage":"Reference must be greater than 3 characters in length"}
{"errorCode":"VALIDATION","errorMessage":"ScheduledAt must be greater than the current Date Time"}
```

feat(validation): Use validation library in API payments initiation endpoint

---

internal/storage/migrations/0-init-schema.sql
internal/storage/migrations/12-add-payment-initiation-adjustment-indexes.go
internal/storage/migrations/migrations.go
internal/storage/payment_initiations.go
internal/storage/payment_initiations_test.go

Fixes: PMNT-62
Quite bad there are some sequential scans
```
Sort  (cost=40.88..40.88 rows=1 width=344)
Sort Key: payment_initiation.created_at DESC, payment_initiation.sort_id DESC
->  Hash Right Join  (cost=26.71..40.87 rows=1 width=344)
Hash Cond: ((old_adj.payment_initiation_id)::text = payment_initiation.id)
Join Filter: (latest_adj.sort_id < old_adj.sort_id)
Filter: (old_adj.id IS NULL)
->  Seq Scan on payment_initiation_adjustments old_adj  (cost=0.00..13.00 rows=300 width=72)
->  Hash  (cost=26.68..26.68 rows=2 width=352)
->  Hash Join  (cost=13.78..26.68 rows=2 width=352)
Hash Cond: (payment_initiation.id = (latest_adj.payment_initiation_id)::text)
->  Seq Scan on payment_initiations payment_initiation  (cost=0.00..12.10 rows=210 width=344)
->  Hash  (cost=13.75..13.75 rows=2 …
```

feat(api): Allow payment initiation list endpoint to query by adjustment status

---

internal/api/services/connector_configs.go
internal/api/services/connector_configs_test.go

Fixes: PMNT-68
Was superceded by https://github.com/formancehq/payments/pull/384 but tests here are still relevant

test(api): inject provider tag into connector config response for SDK

---

internal/api/common/errors.go
internal/models/bank_accounts.go

This PR fixes:
- The bank account IdempotencyKey that was not unique by related bank account created
- Internal server error was not logging the right error
Fixes PMNT-93
Fixes PMNT-94

fix(models): fix bank account ik and internal error not logging

---

internal/connectors/plugins/public/adyen/client/client.go
internal/connectors/plugins/public/adyen/client/client_generated.go
internal/connectors/plugins/public/adyen/client/webhooks.go
internal/connectors/plugins/public/adyen/webhooks.go
internal/connectors/plugins/public/adyen/webhooks_test.go

When we first install Adyen, the CreateWebhooks workflow is called and calls the right function inside adyen plugin. Inside the client, the webhooks are created on the adyen psp and an hmac key is generated and store in memory. When rebooting the worker pod, the hmac key is then empty and cannot be retrieved anymore, hence all the webhooks coming after the reboot are failing the hmac verification
I'm adding the hmac key inside the metadata of the webhooks creation in order to get it when a webhook is coming inside the config
Fixes PMNT-107

fix(adyen): fix missing hmac key when pod is restarted

---

internal/connectors/engine/activities/activity.go
internal/connectors/engine/activities/events_send_task_updated.go
internal/connectors/engine/workflow/create_bank_account_test.go
internal/connectors/engine/workflow/create_payout_test.go
internal/connectors/engine/workflow/create_transfer_test.go
internal/connectors/engine/workflow/create_webhooks_test.go
internal/connectors/engine/workflow/fetch_accounts_test.go
internal/connectors/engine/workflow/fetch_balances_test.go
internal/connectors/engine/workflow/fetch_external_accounts_test.go
internal/connectors/engine/workflow/fetch_others_test.go
internal/connectors/engine/workflow/fetch_payments_test.go
internal/connectors/engine/workflow/handle_webhooks_test.go
internal/connectors/engine/workflow/install_connector_test.go
internal/connectors/engine/workflow/plugin_workflow_test.go
internal/connectors/engine/workflow/poll_payout_test.go
internal/connectors/engine/workflow/poll_transfer_test.go
internal/connectors/engine/workflow/reset_connector_test.go
internal/connectors/engine/workflow/reverse_payout_test.go
internal/connectors/engine/workflow/reverse_transfer_test.go
internal/connectors/engine/workflow/send_events.go
internal/connectors/engine/workflow/send_events_test.go
internal/connectors/engine/workflow/terminate_schedules_test.go
internal/connectors/engine/workflow/terminate_workflows_test.go
internal/connectors/engine/workflow/uninstall_connector_test.go
internal/connectors/engine/workflow/update_payment_initiation_from_payment_test.go
internal/connectors/engine/workflow/update_tasks.go
internal/connectors/plugins/public/atlar/bank_account_creation_test.go
internal/events/task.go
internal/models/tasks.go
pkg/events/event.go

This PR does two things:
- Add events when a task is updated
- Fix temporal workflow tests when the error wanted is not what we had
When a user creates something via the API (bank accounts, payouts, transfers...), he currently has to poll the api to get the object id when the task is updated which is a bit of a pain. 
When testing temporal workflows, sometimes we test that the workflow returns an error, but we never test what is the error. Some workflows were failing because we missed the mock of a specific functions and the actual error was not catched.
This PR adds a new event for tasks, that the user can listen through nats/webhooks in order to get the created object.
This PR adds specific errors to catch in the test to be sure that we have the right error

feat(events): add task updated events

---

internal/api/router.go
internal/api/v2/router.go
internal/api/v3/router.go

Fixes: CONN-125
The order in which we call middleware is important. What is declared first will be on the "outside".
The OTLP middleware writes to the http response writer and therefore needs to be on the outside, because status code declaration (inside the Recoverer) must take place before the call to Write.

fix(server): Ensure that OTLP middleware doesn't write body before http recoverer can write status code 500
