formancehq/payments

internal/app/api/connectorconfigs.go
internal/app/api/module.go
internal/pkg/configtemplate/template.go
internal/pkg/configtemplate/types.go
internal/pkg/connectors/bankingcircle/config.go
internal/pkg/connectors/currencycloud/config.go
internal/pkg/connectors/dummypay/config.go
internal/pkg/connectors/modulr/config.go
internal/pkg/connectors/stripe/config.go
internal/pkg/connectors/wise/config.go
swagger.yml

feat: list available connectors configs

---

internal/app/connectors/wise/client.go
internal/app/connectors/wise/task_fetch_transfers.go

fix: parse actual timestamp from wise response object

---

internal/app/api/router.go
internal/app/storage/connectors.go

fix: stripe transfer endpoint

---

internal/app/connectors/wise/connector.go
internal/app/connectors/wise/task_fetch_profiles.go
internal/app/connectors/wise/task_fetch_transfers.go

fix: loop on wise accounts

---

internal/app/api/connectorconfigs.go
internal/app/api/stripe.go
swagger.yml

fix: api response encoding to api base

---

openapi.yaml

fix: stripe transfers route definition

---

internal/api/v2/handler_connectors_install.go
internal/connectors/engine/engine.go
internal/connectors/engine/module.go

feat(payments): gracefully stop the engine

---

internal/connectors/engine/workflow/handle_webhooks.go

fix(webhooks): missing missing events when translating webhook

---

internal/api/backend/backend.go
internal/api/backend/backend_generated.go
internal/api/services/payments_create.go
internal/api/v2/handler_payments_create.go
internal/api/v2/router.go
internal/api/v3/handler_payments_create.go
internal/api/v3/router.go
internal/connectors/engine/engine.go
internal/connectors/engine/workflow/create_formance_payment.go
internal/connectors/engine/workflow/workflow.go
internal/models/payment_scheme.go
internal/models/payment_status.go
internal/models/payment_type.go

 feat(payments): add payments creation from API

---

internal/connectors/plugins/public/currencycloud/client/client.go
internal/connectors/plugins/public/currencycloud/client/client_generated.go
internal/connectors/plugins/public/currencycloud/client/contacts.go
internal/connectors/plugins/public/currencycloud/client/payouts.go
internal/connectors/plugins/public/currencycloud/client/transfers.go
internal/connectors/plugins/public/currencycloud/payments.go
internal/connectors/plugins/public/currencycloud/payouts.go
internal/connectors/plugins/public/currencycloud/payouts_test.go
internal/connectors/plugins/public/currencycloud/plugin.go
internal/connectors/plugins/public/currencycloud/plugin_test.go
internal/connectors/plugins/public/currencycloud/transfers.go
internal/connectors/plugins/public/currencycloud/transfers_test.go

feat(currencycloud): add transfer/payout creation

---

internal/connectors/plugins/public/bankingcircle/bank_account_creation.go
internal/connectors/plugins/public/bankingcircle/client/payments.go
internal/connectors/plugins/public/bankingcircle/payouts.go
internal/connectors/plugins/public/bankingcircle/plugin.go
internal/connectors/plugins/public/bankingcircle/transfers.go
internal/connectors/plugins/public/mangopay/transfers.go
internal/models/payments_initiations.go

feat(bankingcircle): add transfer/payout creation

---

internal/connectors/plugins/public/currencycloud/payments_test.go
internal/connectors/plugins/public/modulr/accounts.go
internal/connectors/plugins/public/modulr/accounts_test.go
internal/connectors/plugins/public/modulr/external_accounts.go
internal/connectors/plugins/public/modulr/external_accounts_test.go
internal/connectors/plugins/public/modulr/payments.go
internal/connectors/plugins/public/modulr/payments_test.go
internal/connectors/plugins/public/moneycorp/accounts.go
internal/connectors/plugins/public/moneycorp/accounts_test.go
internal/connectors/plugins/public/moneycorp/client/client.go
internal/connectors/plugins/public/moneycorp/client/client_generated.go
internal/connectors/plugins/public/moneycorp/client/payouts.go
internal/connectors/plugins/public/moneycorp/client/transactions.go
internal/connectors/plugins/public/moneycorp/client/transfers.go
internal/connectors/plugins/public/moneycorp/external_accounts.go
internal/connectors/plugins/public/moneycorp/external_accounts_test.go
internal/connectors/plugins/public/moneycorp/payments.go
internal/connectors/plugins/public/moneycorp/payments_test.go
internal/connectors/plugins/public/moneycorp/payouts.go
internal/connectors/plugins/public/moneycorp/payouts_test.go
internal/connectors/plugins/public/moneycorp/plugin.go
internal/connectors/plugins/public/moneycorp/plugin_test.go
internal/connectors/plugins/public/moneycorp/transfers.go
internal/connectors/plugins/public/moneycorp/transfers_test.go
internal/connectors/plugins/public/moneycorp/utils.go
internal/utils/pagination/paginator.go
internal/utils/pagination/paginator_test.go

feat(*): add payout & transfer for moneycorp and fix pagination (modulr & moneycorp)

---

internal/connectors/plugins/public/wise/accounts.go
internal/connectors/plugins/public/wise/accounts_test.go
internal/connectors/plugins/public/wise/client/recipient_accounts.go
internal/connectors/plugins/public/wise/external_accounts.go
internal/connectors/plugins/public/wise/external_accounts_test.go
internal/connectors/plugins/public/wise/payments.go
internal/connectors/plugins/public/wise/payments_test.go
internal/connectors/plugins/public/wise/plugin_test.go

feat(wise): simplify loops and add tests

---

internal/connectors/plugins/errors.go
internal/connectors/plugins/public/wise/payments.go
internal/connectors/plugins/public/wise/payouts.go
internal/connectors/plugins/public/wise/payouts_test.go
internal/connectors/plugins/public/wise/plugin.go
internal/connectors/plugins/public/wise/plugin_test.go
internal/connectors/plugins/public/wise/transfers.go
internal/connectors/plugins/public/wise/transfers_test.go
internal/connectors/plugins/public/wise/utils.go
internal/connectors/plugins/public/wise/webhooks.go

feat(wise): add transfer/payout implementation

---

cmd/root.go
internal/api/v2/handler_connectors_list.go
internal/api/v3/handler_connectors_uninstall.go
internal/connectors/engine/engine.go
internal/connectors/engine/module.go
internal/connectors/engine/workflow/terminate_workflows.go
internal/connectors/engine/workflow/uninstall_connector.go
internal/connectors/engine/workflow/workflow.go
internal/models/connectors.go
internal/storage/connectors.go
internal/storage/connectors_test.go
internal/storage/migrations/0-init-schema.sql
internal/storage/storage.go
internal/storage/storage_generated.go

feat(connectors): uninstall in background and send accepted

---

internal/api/backend/backend.go
internal/api/backend/backend_generated.go
internal/api/services/payment_initiations_approve.go
internal/api/services/payment_initiations_create.go
internal/api/services/payment_initiations_retry.go
internal/api/v2/handler_transfer_initiations_create.go
internal/api/v2/handler_transfer_initiations_retry.go
internal/api/v2/handler_transfer_initiations_update_status.go
internal/api/v3/handler_payment_initiations_approve.go
internal/api/v3/handler_payment_initiations_create.go
internal/api/v3/handler_payment_initiations_retry.go
internal/connectors/engine/engine.go
internal/connectors/engine/workflow/create_payout.go
internal/connectors/engine/workflow/create_transfer.go

feat(*): transfer and payouts are sent in background in v3

---

internal/api/v3/handler_connectors_install.go
internal/connectors/engine/engine.go
internal/connectors/engine/module.go
internal/connectors/engine/workers.go
internal/connectors/engine/workflow/install_connector.go

feat(install): launch tasks in background

---

internal/connectors/plugins/public/stripe/client/client.go
internal/connectors/plugins/public/stripe/client/client_generated.go
internal/connectors/plugins/public/stripe/client/payouts.go
internal/connectors/plugins/public/stripe/client/transfers.go
internal/connectors/plugins/public/stripe/payouts.go
internal/connectors/plugins/public/stripe/payouts_test.go
internal/connectors/plugins/public/stripe/plugin.go
internal/connectors/plugins/public/stripe/plugin_test.go
internal/connectors/plugins/public/stripe/transfers.go
internal/connectors/plugins/public/stripe/transfers_test.go
internal/connectors/plugins/public/stripe/utils.go

feat(stripe): add transfer and payout

---

internal/connectors/engine/engine.go
internal/connectors/engine/workflow/create_payout.go
internal/connectors/engine/workflow/create_transfer.go
internal/connectors/engine/workflow/handle_webhooks.go
internal/connectors/engine/workflow/install_connector.go
internal/connectors/engine/workflow/plugin_workflow.go

feat(temporal): ensure workflows and schedules unique per stack

---

internal/connectors/engine/workflow/fetch_accounts.go
internal/connectors/engine/workflow/fetch_balances.go
internal/connectors/engine/workflow/fetch_external_accounts.go
internal/connectors/engine/workflow/fetch_others.go
internal/connectors/engine/workflow/fetch_payments.go
internal/connectors/engine/workflow/terminate_workflows.go
internal/connectors/engine/workflow/workflow.go

feat(temporal): continue as new when fetching too much data

---

internal/connectors/engine/engine.go
internal/storage/accounts_test.go
internal/storage/balances_test.go
internal/storage/bank_accounts_test.go
internal/storage/payment_initiations_test.go
internal/storage/payments_test.go
internal/storage/pools_test.go

fixes: ENG-1529
fixes: ENG-1534

fix: stop waiting for run.Get() calls to complete in case of http client hangup

---

internal/connectors/engine/activities/temporal_schedule_create.go
internal/connectors/engine/workflow/plugin_workflow.go

feat: (scalability) add jitter to temporal schedules

---

internal/connectors/engine/workers.go

feat(temporal): only create default worker if needed

---

Earthfile
go.mod
go.sum
internal/storage/connectors.go
internal/storage/module.go
internal/storage/storage.go
pkg/testserver/server.go
test/e2e/api_bank_accounts_test.go

add earthly steps to run e2e tests by default

fix: run e2e tests on CI by default

---

cmd/root.go
docker-compose.yml

fix: (metrics) ensure connectors metrics registry is initialized

---

internal/storage/accounts.go
internal/storage/accounts_test.go
internal/storage/balances.go
internal/storage/bank_accounts.go
internal/storage/connectors.go
internal/storage/migrations/0-init-schema.sql
internal/storage/payment_initiation_reversals.go
internal/storage/payment_initiations.go
internal/storage/payments.go
internal/storage/pools.go
internal/storage/schedules.go
internal/storage/workflow_instances.go

fix: add autoincrement sort_id to payments v3 tables

---

cmd/root.go
internal/connectors/engine/module.go

feat(temporal): add max concurrent task pollers flag

---

internal/connectors/engine/activities/plugin_uninstall_connector.go
internal/connectors/engine/engine.go
internal/connectors/engine/errors.go
internal/connectors/engine/module.go
internal/connectors/engine/plugins/plugin.go
internal/connectors/plugins/registry/plugins.go
internal/models/config.go

feat(install): do not sent 404 when config is invalid

---

internal/events/bank_account.go

fix: update BankAccount event json tag

---

internal/models/accounts.go
internal/models/balances.go
internal/models/bank_accounts.go
internal/models/connectors.go
internal/models/idempotency.go
internal/models/payment_adjustments.go
internal/models/pools.go

fix: (events) standardize idempotency key length

---

cmd/purge.go
cmd/root.go

feat(purge): add purge command to clean temporal

---

test/e2e/api_connectors_test.go
test/e2e/api_pools_test.go

small changes to e2e to reduce flakeyness of tests

fix: (e2e) workflow timeout

---

internal/api/services/payment_initiations_approve.go
internal/api/services/payment_initiations_create.go
internal/api/services/payment_initiations_retry.go
internal/connectors/engine/engine.go

fix(payments): fix missing delay when scheduling in the future

---

openapi.yaml
openapi/v1-2/v1-2.yaml

relatedPayments can be nullable and this is currently creating an issue with the generated sdk which doesn't handle it.
```
Example of data returned by getTransferInitiation() with the SDK : 
{
"transfer": {
"data": {
"id": "eyJDb25uZWN0b3JJRCI6eyJQcm92aWRlciI6IlNUUklQRSIsIlJlZmVyZW5jZSI6ImNhYWJmZTIwLWMwNGMtNDI2My1hZDYwLTMyNmI0NzExNWE0YSJ9LCJSZWZlcmVuY2UiOiJhY2N0XzFRWGFnaUZ0QjU0ckN3czkifQ",
"reference": "acct_1QXagiFtB54rCws9",
"createdAt": "2024-12-19T15:58:15.558Z",
"scheduledAt": "2025-01-01T00:00:00.000Z",
"description": "Description of my transfer",
"sourceAccountID": "eyJDb25uZWN0b3JJRCI6eyJQcm92aWRlciI6IlNUUklQRSIsIlJlZmVyZW5jZSI6ImNhYWJmZTIwLWMwNGMtNDI2My1hZDYwLTMyNmI0NzExNWE0YSJ9LCJSZWZlcmVuY2UiOiJhY2N0XzFRWGFnaUZ0QjU0ckN3czkifQ",
"destinationAccountID": …
```

fix(openapi): Add nullable on relatedPayments

---

.gitignore
tools/connector-template/README.md
tools/connector-template/connector-template.sh
tools/connector-template/definitions.go
tools/connector-template/main.go
tools/connector-template/template/accounts.gotpl
tools/connector-template/template/balances.gotpl
tools/connector-template/template/capabilities.gotpl
tools/connector-template/template/client/accounts.gotpl
tools/connector-template/template/client/balances.gotpl
tools/connector-template/template/client/client.gotpl
tools/connector-template/template/client/external_accounts.gotpl
tools/connector-template/template/client/payouts.gotpl
tools/connector-template/template/client/transactions.gotpl
tools/connector-template/template/client/transfers.gotpl
tools/connector-template/template/config.gotpl
tools/connector-template/template/currencies.gotpl
tools/connector-template/template/external_accounts.gotpl
tools/connector-template/template/payments.gotpl
tools/connector-template/template/payouts.gotpl
tools/connector-template/template/plugin.gotpl
tools/connector-template/template/transfers.gotpl
tools/connector-template/template/utils.gotpl
tools/connector-template/template/workflow.gotpl

feat(tools): add connector code generation from template

---

internal/api/backend/backend.go
internal/api/backend/backend_generated.go
internal/api/services/connectors_reset.go
internal/api/v2/handler_connectors_reset.go
internal/api/v2/handler_connectors_reset_test.go
internal/api/v3/handler_connectors_reset.go
internal/api/v3/handler_connectors_reset_test.go
internal/connectors/engine/activities/activity.go
internal/connectors/engine/activities/storage_connectors_get.go
internal/connectors/engine/activities/storage_connectors_schedule_for_deletion.go
internal/connectors/engine/engine.go
internal/connectors/engine/workflow/reset_connector.go
internal/connectors/engine/workflow/send_events.go
internal/connectors/engine/workflow/uninstall_connector.go
internal/connectors/engine/workflow/workflow.go
openapi/v3/v3-api.yaml
pkg/testserver/api.go
test/e2e/api_connectors_test.go

feat(connector): fix reset connector api

---

internal/connectors/engine/engine.go
internal/connectors/engine/util.go
internal/connectors/engine/workers.go
internal/connectors/engine/workflow/create_bank_account.go
internal/connectors/engine/workflow/create_payout.go
internal/connectors/engine/workflow/create_transfer.go
internal/connectors/engine/workflow/create_webhooks.go
internal/connectors/engine/workflow/fetch_accounts.go
internal/connectors/engine/workflow/fetch_balances.go
internal/connectors/engine/workflow/fetch_external_accounts.go
internal/connectors/engine/workflow/fetch_others.go
internal/connectors/engine/workflow/fetch_payments.go
internal/connectors/engine/workflow/handle_webhooks.go
internal/connectors/engine/workflow/install_connector.go
internal/connectors/engine/workflow/plugin_workflow.go
internal/connectors/engine/workflow/reset_connector.go
internal/connectors/engine/workflow/utils.go

feat: (workers) use default task queue for everything

---

pkg/testserver/api.go
test/e2e/api_connectors_test.go

test(configs): Add integration test for connector configs endpoint

---

.codecov.yml

just excluding generated code from code coverage

fix: add generated files to code-coverage ignore list

---

internal/api/v3/handler_schedules_get.go
internal/api/v3/handler_schedules_get_test.go
internal/api/v3/router.go
openapi.yaml
pkg/testserver/api.go
test/e2e/api_connectors_test.go

feat(schedules): add get endpoint for single schedule

---

internal/connectors/plugins/public/stripe/client/accounts.go
internal/connectors/plugins/public/stripe/client/external_accounts.go
internal/connectors/plugins/public/stripe/client/payments.go

fix(connectors): handle no results case from Stripe API list endpoints

---

internal/connectors/engine/activities/errors.go
internal/connectors/plugins/public/mangopay/bank_account_creation.go
internal/connectors/plugins/public/mangopay/plugin.go

fix(mangopay): handle missing metadata as non-retryable error in mangopay bank account creation

---

Earthfile
internal/storage/pools.go
internal/storage/pools_test.go

Fixes PMNT-1
Fixes ENG-1651
Fixes ENG-1650

feat(pools): more filters when listing

---

cmd/root.go
cmd/worker.go
internal/worker/module.go
test/e2e/api_connectors_test.go

feat(temporal): allow finer tuning of temporal worker task slots

---

internal/connectors/engine/activities/errors.go
internal/connectors/engine/activities/plugin_create_bank_account_test.go
internal/connectors/plugins/public/mangopay/bank_account_creation.go
internal/connectors/plugins/public/mangopay/bank_account_creation_test.go
internal/connectors/plugins/public/mangopay/plugin.go
internal/models/errors.go
internal/models/errors_test.go

feat(temporal): create generic connector metadata missing error type to reduce custom error types

---

CONTRIBUTING.md

feat(plugins): add contributing doc

---

internal/api/v2/handler_connectors_update_config.go
internal/api/v2/handler_connectors_update_config_test.go
internal/api/v2/router.go
pkg/testserver/api.go
test/e2e/api_connectors_test.go

fix(v2): fix missing update connector route

---

openapi.yaml
openapi/v1-2/v1-2.yaml

fix(transfer-initiation): Add missing provider in TransferInitiation

---

internal/connectors/plugins/public/atlar/config.go
openapi.yaml

fix(atlar): fix json tag with backward compatibility

---

openapi.yaml
openapi/v1-2/v1-2.yaml

fix(openapi): remove not valid status when updating transfers

---

openapi.yaml
openapi/v1-2/v1-2.yaml
openapi/v3/v3-schemas.yaml

fix(apispec): Make error an optional field in API v1 specs for payments objects

---

internal/api/services/connector_configs.go
internal/api/services/connector_configs_test.go
internal/api/v2/handler_accounts_create.go
internal/api/v2/handler_bank_accounts_create.go
internal/api/v2/handler_bank_accounts_forward_to_connector.go
internal/api/v2/handler_payments_create.go
internal/connectors/engine/engine.go
internal/connectors/engine/engine_test.go
internal/connectors/engine/plugins/plugin.go
internal/connectors/engine/plugins/plugin_generated.go
internal/connectors/engine/workers.go
internal/connectors/engine/workflow/main_test.go
internal/events/account.go
internal/events/balance.go
internal/events/bank_account.go
internal/events/payment.go
internal/models/accounts.go
internal/models/connectors.go
internal/models/payment_initiations.go
internal/models/payments.go
internal/storage/connectors.go
internal/storage/connectors_test.go
internal/storage/migrations/13-connector-providers-lowercase.sql
internal/storage/migrations/migrations.go
internal/storage/migrations/migrations_test.go
test/e2e/api_connectors_test.go

fix(connectors): provider should always be lowercase in v3

---

internal/api/services/payment_initiations_create.go
internal/api/services/payment_initiations_create_test.go
internal/connectors/engine/activities/activity.go
internal/connectors/engine/activities/events_send_payment_initiation.go
internal/connectors/engine/activities/events_send_payment_initiation_adjustment.go
internal/connectors/engine/activities/events_send_payment_initiation_related_payments.go
internal/connectors/engine/engine.go
internal/connectors/engine/engine_generated.go
internal/connectors/engine/workflow/create_payout_test.go
internal/connectors/engine/workflow/create_transfer_test.go
internal/connectors/engine/workflow/poll_payout_test.go
internal/connectors/engine/workflow/poll_transfer_test.go
internal/connectors/engine/workflow/reverse.go
internal/connectors/engine/workflow/reverse_payout_test.go
internal/connectors/engine/workflow/reverse_transfer_test.go
internal/connectors/engine/workflow/send_events.go
internal/connectors/engine/workflow/send_events_test.go
internal/connectors/engine/workflow/utils.go
internal/events/payment.go
internal/events/payment_initiation.go
internal/models/payment_initation_related_payments.go
internal/models/payment_initiation_adjustments.go
internal/models/payment_initiations.go
pkg/events/event.go
test/e2e/api_connectors_test.go
test/e2e/api_payment_initiations_test.go

feat(*): add events for payment initiations

---

internal/connectors/engine/errors.go
internal/connectors/engine/workflow/create_bank_account.go
internal/connectors/engine/workflow/create_payout.go
internal/connectors/engine/workflow/create_transfer.go
internal/connectors/engine/workflow/errors.go
internal/connectors/engine/workflow/fetch_accounts.go
internal/connectors/engine/workflow/fetch_balances.go
internal/connectors/engine/workflow/fetch_external_accounts.go
internal/connectors/engine/workflow/fetch_payments.go
internal/connectors/engine/workflow/handle_webhooks.go
internal/connectors/engine/workflow/poll_payout.go
internal/connectors/engine/workflow/poll_transfer.go
internal/connectors/engine/workflow/reverse_payout.go
internal/connectors/engine/workflow/reverse_transfer.go
internal/models/accounts.go
internal/models/balances.go
internal/models/errors.go
internal/models/payment_test.go
internal/models/payments.go
internal/utils/assets/assets.go

feat(temporal): return an error when error translating PSP data

---

internal/api/v3/handler_pools_balances_at.go
internal/api/v3/handler_pools_balances_at_test.go

feat(api): Return a validation error when attempting to fetch future pool balances

---

internal/models/payment_adjustments.go

fix(payments): Ensure that payment adjustment references are persisted

---

internal/models/bank_accounts_test.go

Found this small issue while running precommit on my branch :)

fix: some tests were failing, probably because of a conflict

---

internal/connectors/plugins/public/qonto/accounts.go
internal/connectors/plugins/public/qonto/accounts_test.go
internal/connectors/plugins/public/qonto/balances_test.go
internal/connectors/plugins/public/qonto/client/beneficiaries.go
internal/connectors/plugins/public/qonto/client/client.go
internal/connectors/plugins/public/qonto/client/transactions.go
internal/connectors/plugins/public/qonto/external_accounts.go
internal/connectors/plugins/public/qonto/external_accounts_test.go
internal/connectors/plugins/public/qonto/payments.go
internal/connectors/plugins/public/qonto/payments_test.go

According to AI, it's actually the only constant like this (there are others, but they're more enums kind of things

fix: change const case to camelCase

---

internal/connectors/engine/workflow/fetch_accounts_test.go
internal/connectors/engine/workflow/fetch_balances_test.go
internal/connectors/engine/workflow/fetch_external_accounts_test.go
internal/connectors/engine/workflow/fetch_others_test.go
internal/connectors/engine/workflow/fetch_payments.go
internal/connectors/engine/workflow/fetch_payments_test.go
internal/connectors/engine/workflow/instances.go
internal/connectors/engine/workflow/main_test.go
internal/connectors/engine/workflow/workflow.go
internal/worker/module.go

fix(polling):  Ensure non-periodic tasks continue polling after ContinueAsNew

---

.envrc
go.mod
go.sum
internal/storage/error.go

fix(BAN-40): use go-lib postgres errors to figure out storage error types

---

go.mod
internal/connectors/engine/engine.go
internal/connectors/plugins/base_plugin.go
internal/models/plugin.go

Allow big sized webhooks to be truncated and handled in parallel

feat(webhooks): allow big sized webhooks

---

internal/connectors/engine/engine.go
internal/connectors/engine/engine_test.go

fix: Handle invalid json sent to connector install endpoint with 400

---

CONTRIBUTING.md
README.md

docs: Updating docs for the new dcos.formance.com site. Some cleanup

---

internal/api/v3/handler_schedules_list.go
internal/api/v3/handler_schedules_list_test.go
internal/api/v3/utils.go
test/e2e/api_connectors_test.go

fix(schedules): Filter schedules by connectorID in list endpoint
